services:
  web:
    image: node:19
    volumes: 
      - .:/app
    working_dir: /app
    ports: 
      - '5173:5173'
    expose: 
      - 5173
    command: npm run dev
  test:
    image: node:19
    volumes:
      - .:/app
    working_dir: /app
    command: npm run test:unit